name: Build app and deploy to tencent
on:
  #监听push操作
  push:
    branches:
      # master分支，你也可以改成其他分支
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.6'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.25.1
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run start:build-wp
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GD_BE }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: dist # 这是要复制到服务器的文件夹名称
          REMOTE_HOST: '124.223.56.117' # 公网地址
          REMOTE_USER: root # 登录后默认为 root 用户
          TARGET: /www/wwwroot/GD-BE/ # 打包后的 dist 文件夹将放在 /root/node-server
